In [1]:
from generation.generation import diviner
from my_functions1 import extractor
from my_functions import responser

import torch


import sys
sys.path.insert(0, "/notebook/cqas/generation/gpt-2-Pytorch")
sys.path.insert(0, "/notebook/cqas/generation/Student")
sys.path.insert(0, "/notebook/cqas/generation/pytorch_transformers")

from cam_summarize import load_cam_model
from text_gen_big import load_big_model
from text_gen import load_small_model

#device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
#LM_CAM = load_cam_model(device)
#Cam = diviner(tp = 'cam', model = LM_CAM, device = device)

device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
LM_SMALL = load_small_model(device)
GPT2Small = diviner(tp = 'small', model = LM_SMALL, device = device)

device = torch.device("cuda:3" if torch.cuda.is_available() else "cpu")
LM_BIG, tokenizer_big = load_big_model(device)
GPT2Big = diviner(tp = 'big', model = LM_BIG, tokenizer = tokenizer_big, device = device)

Templ = diviner(tp = 'templates', model = '', device = device)

ModuleNotFoundError: No module named 'generation'

In [ ]:
list_of_template_answers = []
list_of_given_qwestions = ["What is better Toyota or Honda ?", "What is better Nokia or Motorolla ?"]

In [107]:
my_diviner = Templ


answer = generate_answer(my_extractor, my_diviner, "What is better for deep learning Python or Matlab?")

9
9
in extractor get params 0
LayerContextWordEmbeddingsBert 2
LayerContextWordEmbeddingsBert2 2
LayerContextWordEmbeddingsBert3 2
LayerContextWordEmbeddingsBert4 2
LayerContextWordEmbeddingsBert5 2
LayerContextWordEmbeddingsBert6 2
LayerContextWordEmbeddingsBert7 2
LayerContextWordEmbeddingsBert8 2
LayerContextWordEmbeddingsBert9 2
extract_objects_predicates tags [['O', 'O', 'B-PREDFULL', 'O', 'O', 'O', 'B-OBJ', 'O', 'O']]
['python']
['better']
We try to use spacy
split_sent ['what', 'is', 'better', 'for', 'deep', 'learning', 'python', 'or', 'matlab?']
tokens  ['What', 'is', 'better', 'for', 'deep', 'learning', 'Python', 'or', 'Matlab', '?']
or simple split_sent 7
Python Matlab
9
len(obj1), len(obj2) 6 6
obj1, obj2, predicates Python Matlab ['better']
aspects ['better']
weights [1]
get url
params {'objectA': 'Python', 'objectB': 'Matlab', 'fs': 'true', 'aspect1': 'better', 'weight1': 1}
create fro json predicates ['better']
create fro json self.predicates better
aspects  ['quicker to 

In [123]:
import pandas as pd 
  
# reading csv file  
ds = pd.read_csv("Evaluation dataset - Sheet1 (1).csv") 
list_of_target1 = ds['Q1']
list_of_target1 = ds['Q2']

In [125]:
list_of_target1[9]

'I would prefer a Laptop. You can:\nIf you are buying a laptop with a fine Graphics Card, play games that a smartphone cant support.\nGo coding. Laptops provide a much broader variety of scope as you can make it a Virtual Box(having two or more Operating systems) and download open source pgms like anaconda, open cv,etc.\nBigger Screen. Watching movies takes a huge step forward when its a bigger screen and better sound effects. You can argue that the latest smartphones have all these capabilities but the average power drain comparison puts laptops ahead.\nHuge storage space. Your 500GB or higher internal hard drive can store all the required stuff you will need.'

In [121]:
import os


text_generator_for_out("Python is better than Matlab, because it is quicker to develop code, easier.", LM_BIG)

  0%|          | 0/200 [00:00<?, ?it/s]

text_generator_for_out
exist3
exist4
exist


100%|██████████| 200/200 [00:08<00:00, 22.80it/s]

qu
======================================== SAMPLE 1 ========================================
in big gen2  If you need to make a quick change in your code and you need to quickly run the test suite, Matlab is better than Python because it is faster to develop and run.

There are many other factors that I haven't mentioned here, but I hope that you will find this list of Python vs. Matlab differences interesting.

If you want to learn more about Python, I would highly recommend you to check out my book, Python for Beginners. It's free and I've written it for you. But if you are looking for something more practical, then I would recommend taking a look at the Python for Business book.

If you have any questions, please don't hesitate to ask them in the comment section below.

Thanks for reading!<|endoftext|>The last time I was in the US, I found myself in a small bar in a tiny town in the middle of nowhere, talking with an American who was talking about his first trip to the US. He
qu2
q

" If you need to make a quick change in your code and you need to quickly run the test suite, Matlab is better than Python because it is faster to develop and run.\n\nThere are many other factors that I haven't mentioned here, but I hope that you will find this list of Python vs. Matlab differences interesting.\n\nIf you want to learn more about Python, I would highly recommend you to check out my book, Python for Beginners. It's free and I've written it for you. But if you are looking for something more practical, then I would recommend taking a look at the Python for Business book.\n\nIf you have any questions, please don't hesitate to ask them in the comment section below.\n\nThanks for reading!<|endoftext|>The last time I was in the US, I found myself in a small bar in a tiny town in the middle of nowhere, talking with an American who was talking about his first trip to the US. He"

In [120]:
from GPT2.model import (GPT2LMHeadModel)
from GPT2.utils import load_weight
from GPT2.config import GPT2Config
from GPT2.sample import sample_sequence
from GPT2.encoder import get_encoder


def text_generator_for_out(text, model, length = 200, temperature = 0.7, top_k = 40):
    print("text_generator_for_out")
    
    device = torch.device("cuda:3" if torch.cuda.is_available() else "cpu")
    print ("exist3")
    # Load Model
    enc = get_encoder()
    print ("exist4")

    quiet = False
    print ("exist")
    length = 200

    if length == -1:
        length = 1024 // 2
    elif length > 1024:
        raise ValueError("Can't get samples longer than window size: %s" % 1024)

    context_tokens = enc.encode(text)

    generated = 0
    for _ in range(1):
        out = sample_sequence(
            model=model, length=length,
            context=context_tokens,
            start_token=None,
            batch_size=1,
            temperature=temperature, top_k=top_k, device=device
        )
        out = out[:, len(context_tokens):].tolist()
        for i in range(1):
            generated += 1
            text = enc.decode(out[i])
            if quiet is False:
                print ("qu")
                print("=" * 40 + " SAMPLE " + str(generated) + " " + "=" * 40)
            print("in big gen2", text)
            print ("qu2")
            print ("qu3")
            return text

In [112]:
answer

'i came to the conclusion that python is better, because: quicker to develop code, quicker, matplotlib, easier.. But i should tell you that matlab is: faster, better for scientific computing, experience.'

In [4]:
import requests
URL = 'http://ltdemos.informatik.uni-hamburg.de/cam-api'
#proxies = {"http": "http://185.46.212.97:10015/","https": "https://185.46.212.98:10015/",}
params = {
            'objectA': 'Moscow',
            'objectB': 'London',
            'fs': str(True).lower()}
response = requests.get(url=URL, params=params)#, proxies=proxies)

In [8]:
import json
import gzip
import random

list_qw = []
   
with open('/notebook/dataset/QuoraDuplicate_comapratives-2.json', 'r') as fin:
    count = 0
    for line in fin:
        line = line.strip().split("\t")
        if (count < 200):
            try:
                l = "\"or\""
                if (line[4] == "\"or\""):
                    list_qw.append(line[1])
            except:
                print ("lin", line)
            count += 1

In [10]:
len(list_qw)

69

In [9]:
list_of_qwestions = ['Which is better: Windows 7 or Windows 8?', "Do you prefer charcoal or gas grills when cooking food?", "Which is better for a homeowner, an electric or a gas lawn mower?"]

In [40]:
list_of_answers = []
list_of_answers.append("The answer depends on you. From a technical standpoint, Window 7 is less stable and uses system resources less efficiently than Windows 8. Additionally Windows 8 can run Metro apps that cannot be used on Windows 7 machines. Basically, Windows 8 can do everything that Windows 7 can do and more as--mentioned by Sean Phạm.You do however have to learn some key new interface changes--for example hot corners and the start screen. These have a reputation for not being intuitive for mouse and keyboard users. I tend to disagree, because I use Windows 8 on a daily basis on my non-touchscreen desktop and laptop, for coding, gaming, web browsing, document authoring and other common tasks. I don't feel any slower with Windows 8 than Windows 7.If you're willing to learn the interface changes, then Windows 8 is a win-win situation. Otherwise you might want to stick with Windows 7 and forgo the stability improvements and other small improvements of Windows 8.")
list_of_answers.append("Gas bbq is clean, quick, and gets you out of the kitchen onto the deck in a more sociable way. It is however a little soulless. It’s mostly about the destination. Charcoal cooking is a far more social event, where a group of folk can stand around the flames and enjoy the whole journey, savouring the destination, the anticipation, the aroma, the flames, the feeling of comradery, and hearing the meat cooking, and smelling the meat and other foods under your tender care. It has soul, but it is slow, not as tidy, and far far more fun.")
list_of_answers.append("Gas, hands down. While I appreciate staying green, electric mowers just don’t have the power to cut through tough grass or weeds, to mulch clippings, or to mow high or thick grass if you missed a week. Corded versions are better than battery powered (there’s nothing worse than running out of juice halfway through the mowing), but then you’ll have to have a long extension cord to reach all areas of the lawn, and you’ll also have to be conscientious of where the cord is so you don’t run over it. Gas mowers have power, and if the tank runs out, you can refill it and keep ongoing immediately while you’re still waiting on a battery mower to charge. There’s no cord to worry about either.")

In [41]:
list_of_answers_template = []
list_of_answers_template.append("i came to the conclusion that windows 8 is better, because: first, quicker, second, easier, third, smoother, fourth, faster.. But i should tell you that 7 is: first, greater, second, lighterfaster, third, worse for microsoft.")
list_of_answers_template.append("after much thought, I realized that  charcoal is better, because: lighter, greater, cheaper, taste.. But you should know that gas is: cleaner, easier to use, faster, quicker.")
list_of_answers_template.append("")

In [13]:
list_of_answers_small = []

my_diviner = GPT2Small

for elem in list_of_qwestions:
    print (elem)
    answer = generate_answer(my_extractor, my_diviner, elem)
    list_of_answers_small.append(answer)

Which is better: Windows 7 or Windows 8?
9
9
in extractor get params 0
LayerContextWordEmbeddingsBert 2
LayerContextWordEmbeddingsBert2 2
LayerContextWordEmbeddingsBert3 2
LayerContextWordEmbeddingsBert4 2
LayerContextWordEmbeddingsBert5 2
LayerContextWordEmbeddingsBert6 2
LayerContextWordEmbeddingsBert7 2
LayerContextWordEmbeddingsBert8 2
LayerContextWordEmbeddingsBert9 2
extract_objects_predicates tags [['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']]
[]
[]
We try to use spacy
split_sent ['which', 'is', 'better:', 'windows', '7', 'or', 'windows', '8?']
tokens  ['Which', 'is', 'better', ':', 'Windows', '7', 'or', 'Windows', '8', '?']
or index doc snet 6
begin end  5 6 7
obj1 spacy doc sent 7
or index doc snet 6
begin end  7 9 Windows 8
obj2 spacy doc sent Windows 8
9
len(obj1), len(obj2) 1 9
obj1, obj2, predicates 7 Windows 8 []
aspects []
weights []
get url
params {'objectA': '7', 'objectB': 'Windows 8', 'fs': 'true'}


  0%|          | 0/200 [00:00<?, ?it/s]

create fro json predicates []
create fro json self.predicates 
aspects  ['quicker', 'easier', 'smoother', 'faster'] ['greater', 'lighterfaster', 'worse for microsoft']
2
winnder: windows 8  other: 7
acpect winner  quicker, easier, smoother, faster
acpect other  greater, lighterfaster, worse for microsoft
type  small
winnder: windows 8  other: 7
acpect winner  quicker, easier, smoother, faster
acpect other  greater, lighterfaster, worse for microsoft
self predicate  better
answer begin:  The windows 8 is better than 7. The reason is quicker, easier, smoother, faster. 
self type small
answer_begin The windows 8 is better than 7. The reason is quicker, easier, smoother, faster. 
text_generator_for_out /notebook/cqas/generation/gpt-2-Pytorch
exist3
exist4
exist
Do you prefer charcoal or gas grills when cooking food?
9
9
in extractor get params 0
LayerContextWordEmbeddingsBert 2
LayerContextWordEmbeddingsBert2 2
LayerContextWordEmbeddingsBert3 2
LayerContextWordEmbeddingsBert4 2
LayerContex

split_sent ['do', 'you', 'prefer', 'charcoal', 'or', 'gas', 'grills', 'when', 'cooking', 'food?']
tokens  ['Do', 'you', 'prefer', 'charcoal', 'or', 'gas', 'grills', 'when', 'cooking', 'food', '?']
or simple split_sent 4
charcoal gas
9
len(obj1), len(obj2) 8 3
obj1, obj2, predicates charcoal gas []
aspects []
weights []
get url
params {'objectA': 'charcoal', 'objectB': 'gas', 'fs': 'true'}


  0%|          | 0/200 [00:00<?, ?it/s]

create fro json predicates []
create fro json self.predicates 
aspects  ['greater', 'lighter', 'cheaper', 'taste'] ['easier to use', 'cleaner', 'faster', 'quicker']
2
winnder: charcoal  other: gas
acpect winner  greater, lighter, cheaper, taste
acpect other  easier to use, cleaner, faster, quicker
type  small
winnder: charcoal  other: gas
acpect winner  greater, lighter, cheaper, taste
acpect other  easier to use, cleaner, faster, quicker
self predicate  better
answer begin:  The charcoal is better than gas. The reason is greater, lighter, cheaper, taste. 
self type small
answer_begin The charcoal is better than gas. The reason is greater, lighter, cheaper, taste. 
text_generator_for_out /notebook/cqas/generation/gpt-2-Pytorch
exist3
exist4
exist
Which is better for a homeowner, an electric or a gas lawn mower?
9
9
in extractor get params 0
LayerContextWordEmbeddingsBert 2
LayerContextWordEmbeddingsBert2 2
LayerContextWordEmbeddingsBert3 2
LayerContextWordEmbeddingsBert4 2
LayerContext

split_sent ['which', 'is', 'better', 'for', 'a', 'homeowner,', 'an', 'electric', 'or', 'a', 'gas', 'lawn', 'mower?']
tokens  ['Which', 'is', 'better', 'for', 'a', 'homeowner', ',', 'an', 'electric', 'or', 'a', 'gas', 'lawn', 'mower', '?']
or simple split_sent 9
electric a
9
len(obj1), len(obj2) 8 1
obj1, obj2, predicates electric a ['better']
aspects ['better']
weights [1]
get url
params {'objectA': 'electric', 'objectB': 'a', 'fs': 'true', 'aspect1': 'better', 'weight1': 1}


  0%|          | 0/200 [00:00<?, ?it/s]

create fro json predicates ['better']
create fro json self.predicates better
aspects  ['safer to use', 'easier to care for and causing much less air pollution', 'larger', 'lighter'] ['simpler', 'cheaper', 'smarter', 'healthier']
2
winnder: electric  other: a
acpect winner  safer to use, easier to care for and causing much less air pollution, larger, lighter
acpect other  simpler, cheaper, smarter, healthier
type  small
winnder: electric  other: a
acpect winner  safer to use, easier to care for and causing much less air pollution, larger, lighter
acpect other  simpler, cheaper, smarter, healthier
self predicate  better
answer begin:  The electric is better than a. The reason is safer to use, easier to care for and causing much less air pollution, larger, lighter. 
self type small
answer_begin The electric is better than a. The reason is safer to use, easier to care for and causing much less air pollution, larger, lighter. 
text_generator_for_out /notebook/cqas/generation/gpt-2-Pytorch
e

In [11]:
list_of_answers_small

['smth wrong in answer generation, please try again',
 'smth wrong in answer generation, please try again',
 'smth wrong in answer generation, please try again']

In [32]:
!pip3 install rouge/requirements.txt

ERROR: Invalid requirement: 'rouge/requirements.txt'
Hint: It looks like a path. File 'rouge/requirements.txt' does not exist.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [33]:
! pip3 install rouge-score

You should consider upgrading via the 'pip install --upgrade pip' command.


## Rouge ##

In [396]:
from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)
scores = scorer.score('The quick brown dog jumps over the lazy fox',
                      'The quick brown dog jumps over the lazy fox.')
print (scores)

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)
scores = scorer.score('The quick brown dog jumps over the lazy fox',
                      'The fast hazel hound skips above the inactive tod.')
print (scores)

{'rouge1': Score(precision=1.0, recall=1.0, fmeasure=1.0), 'rouge2': Score(precision=1.0, recall=1.0, fmeasure=1.0)}
{'rouge1': Score(precision=0.2222222222222222, recall=0.2222222222222222, fmeasure=0.2222222222222222), 'rouge2': Score(precision=0.0, recall=0.0, fmeasure=0.0)}


In [397]:
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)
scores = scorer.score('The quick brown dog jumps over the lazy fox',
                      'Just the place for a Snark the Bellman cried')
print (scores)

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)
scores = scorer.score('The fast hazel hound skips above the inactive tod',
                      'Just the place for a Snark the Bellman cried')
print (scores)



{'rouge1': Score(precision=0.2222222222222222, recall=0.2222222222222222, fmeasure=0.2222222222222222), 'rouge2': Score(precision=0.0, recall=0.0, fmeasure=0.0)}
{'rouge1': Score(precision=0.2222222222222222, recall=0.2222222222222222, fmeasure=0.2222222222222222), 'rouge2': Score(precision=0.0, recall=0.0, fmeasure=0.0)}


In [42]:
scorer.score(list_of_answers[0], list_of_answers_template[0])

{'rouge1': Score(precision=0.4, recall=0.08235294117647059, fmeasure=0.13658536585365855),
 'rougeL': Score(precision=0.22857142857142856, recall=0.047058823529411764, fmeasure=0.07804878048780488)}

## bert embeddings

In [1]:
from bert_serving.client import BertClient


In [4]:
!pwd

/notebook/cqas


In [1]:
import tensorflow as tf
with tf.Session() as sess:
    saver = tf.train.import_meta_graph('/notebook/uncased_L-12_H-768_A-12/bert_model.ckpt.meta')
    saver.restore(sess, "/notebook/uncased_L-12_H-768_A-12/bert_model.ckpt")

/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/pyth

Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /notebook/uncased_L-12_H-768_A-12/bert_model.ckpt


In [ ]:
! bert-serving-start -model_dir "/notebook/uncased_L-12_H-768_A-12/" -num_worker=1

/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/pyth

In [1]:
!pip3 install bert-serving-client

You should consider upgrading via the 'pip install --upgrade pip' command.


In [14]:
from bert_serving.client import BertClient

In [ ]:
with BertClient() as bc:
    # encode untokenized sentences
    bc.encode(['First do it',
              'then do it right',
              'then do it better'])

In [2]:
bc = BertClient()

In [4]:
bc = BertClient()
a = bc.encode(['First do it', 'then do it right', 'then do it better'])

## Bert embeddings

In [1]:
! nvcc --version

/bin/sh: 1: nvcc: not found


In [8]:
from bert_embedding import BertEmbedding

Bert embedding лучше учитывает контекст (так, что в словах "Я лублю яблоки" "Мне нравятся яблочные макбуки" Я - разное
В случае с service bert I -одинаковое apple одинаковок

I like apple
I like apple macbook

In [9]:
from bert_embedding import BertEmbedding

bert_abstract = """The quick brown dog jumps over the lazy fox.\n The fast hazel hound skips above inactive tod."""
sentences = bert_abstract.split('\n')
bert_embedding = BertEmbedding()
result = bert_embedding(sentences)

In [ ]:
nrgam ('jumps',)
list_of_ngrams Counter({('the',): 2, ('just',): 1, ('place',): 1, ('for',): 1, ('a',): 1, ('snark',): 1, ('bellman',): 1, ('cried',): 1})
[0.6792433]
[0.8161626]
[0.6827992]
[0]
[0.8117111]
[0]
[0]
[0.62362134]

In [461]:
result = bert_embedding(['jumps', 'just', 'a'])
vectors = result[0][1]
vectors1 = result[1][1]
vectors2 = result[2][1]

In [462]:
result[0][0]

['jumps']

In [463]:
cos_lib1 = cosine_similarity(result[0][1][0].reshape(1, -1),result[1][1][0].reshape(1, -1)) #similarity between #the and mother
cos_lib1

array([[0.67924374]], dtype=float32)

In [466]:
cos_lib = cosine_similarity(result[0][1][0].reshape(1, -1),result[2][1][0].reshape(1, -1)) #similarity between #the and mother
cos_lib

array([[0.81171143]], dtype=float32)

In [465]:
cos_lib = cosine_similarity(vectors1[0].reshape(1, -1),vectors2[0].reshape(1, -1)) #similarity between #the and mother
cos_lib

array([[0.7090132]], dtype=float32)

In [243]:
result[1][0][3]

'hound'

In [235]:
vectors = result[0][1]
vectors1 = result[1][1]

In [244]:
print (result[0][0][0], result[1][0][0])
cos_lib = cosine_similarity(vectors[0].reshape(1, -1),vectors1[0].reshape(1, -1)) #similarity between #the and mother
cos_lib

the the


array([[0.7361618]], dtype=float32)

In [245]:
print (result[0][0][1], result[1][0][1])
cos_lib = cosine_similarity(vectors[1].reshape(1, -1),vectors1[1].reshape(1, -1)) #similarity between #cat and dog
cos_lib

quick fast


array([[0.7143352]], dtype=float32)

In [246]:
print (result[0][0][2], result[1][0][2])
cos_lib = cosine_similarity(vectors[2].reshape(1, -1),vectors1[2].reshape(1, -1)) #similarity between #mother and father
cos_lib

brown hazel


array([[0.62875855]], dtype=float32)

In [249]:
print (result[0][0][1], result[1][0][5])
cos_lib = cosine_similarity(vectors[1].reshape(1, -1),vectors1[5].reshape(1, -1)) #similarity between #mother and woman
cos_lib

quick above


array([[0.33970988]], dtype=float32)

In [251]:
print (result[0][0][1], result[1][0][6])
cos_lib = cosine_similarity(vectors[1].reshape(1, -1),vectors1[6].reshape(1, -1)) #similarity between #mother and woman
cos_lib

quick inactive


array([[0.42793167]], dtype=float32)

In [241]:
cosine_similarity(vectors[8].reshape(1, -1),vectors1[3].reshape(1, -1))

array([[0.6268022]], dtype=float32)

In [242]:
result[0][1][2][:10]

array([-0.04705547, -0.3263731 ,  0.5511638 , -0.2329619 ,  0.4126335 ,
        0.4367628 , -0.23546723, -0.10500348, -0.69917077, -0.20350926],
      dtype=float32)

In [55]:
result[1][1][3][:10]

array([-0.48047015,  0.56337065,  0.9621709 , -0.2585507 ,  1.7479268 ,
       -0.00799218, -0.21425778,  0.7045478 , -0.08732209, -0.6905228 ],
      dtype=float32)

In [53]:
result[1][0]

['i', 'work', 'on', 'apple', 'macbook']

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cos_lib = cosine_similarity(vectors[1,:],vectors[2,:])

In [207]:
client = BertClient()
vectors = client.encode(['I like apple.'])
vectors1 = client.encode(['I like apple macbook.'])

In [208]:
vectors.shape

(1, 768)

In [221]:
vectors = client.encode(['the', 'quick', 'brown', 'dog', 'jumps', 'over', 'the', 'lazy', 'fox', '.'])
vectors1 = client.encode(['the','fast', 'hazel', 'hound', 'skips', 'above', 'inactive', 'tod', '.'])
vectors2 = client.encode(['the','woman', 'should', 'be', 'my', 'mother', '.'])

In [222]:
vectors[0].shape

(768,)

In [223]:
vectors1[0].shape

(768,)

In [224]:
from sklearn.metrics.pairwise import cosine_similarity
cos_lib = cosine_similarity(vectors[7].reshape(1, -1),vectors2[1].reshape(1, -1)) #similarity between #mother and #woman
cos_lib

array([[0.8320957]], dtype=float32)

In [163]:
cos_lib = cosine_similarity(vectors[2].reshape(1, -1),vectors1[0].reshape(1, -1)) #similarity between #father and man
cos_lib

array([[0.3891856]], dtype=float32)

In [210]:
cos_lib = cosine_similarity(vectors[0].reshape(1, -1),vectors1[0].reshape(1, -1)) #similarity between #the and the
cos_lib

array([[0.99999994]], dtype=float32)

In [211]:
cos_lib = cosine_similarity(vectors[1].reshape(1, -1),vectors1[1].reshape(1, -1)) #similarity between #quick and fast
cos_lib

array([[0.92401916]], dtype=float32)

In [212]:
cos_lib = cosine_similarity(vectors1[2].reshape(1, -1),vectors[2].reshape(1, -1)) #similarity between #brown and hazel
cos_lib

array([[0.8373927]], dtype=float32)

In [ ]:
если слова в n-граме не совпадают, то 

In [11]:
from nltk.stem import porter
from nltk.tokenize import TweetTokenizer


stemmer = porter.PorterStemmer()
tokenizer = TweetTokenizer()

def create_ngrams(tokens, n): #сюда добавть эмбединги
    ngrams = collections.Counter()
    ngrams_embs = collections.Counter()
    for ngram in (tuple(tokens[i:i + n]) for i in range(len(tokens) - n + 1)):
        ngrams[ngram] += 1
    return ngrams
    

def score(target, prediction, tp = 'Rouge1'):
    return 1

## Count ngrams

In [12]:
for ngram in six.iterkeys(ngrams1):
    print (ngram)

NameError: name 'six' is not defined

In [308]:
for elem in list(ngrams1.keys()):
    print (' '.join(elem))

the quick
quick brown
brown dog
dog jumps
jumps over
over the
the lazy
lazy fox


In [310]:
embeddings1 = bert_embedding([' '.join(elem)for elem in list(ngrams1.keys())])

In [317]:
lazy just
lazy jump

768

In [15]:
tokenizer = TweetTokenizer()
bert_embedding = BertEmbedding()
import collections

str_1 = 'The quick brown dog jumps over the lazy fox'
str_2 = 'The fast hazel hound skips above the inactive tod.'
str_3 = 'Just the place for Snark the Bellman cried'
print ([str_1, str_2])
result = bert_embedding([str_1, str_2, str_3])
ngrams1_embeddings = result[0][1]
ngrams2_embeddings = result[1][1]
ngrams3_embeddings = result[2][1]

ngrams1 = create_ngrams(result[0][0], 2)
ngrams2= create_ngrams(result[1][0], 2)
ngrams3= create_ngrams(result[2][0], 2)

ngrams01 = create_ngrams(result[0][0], 1)
ngrams02= create_ngrams(result[1][0], 1)
ngrams03= create_ngrams(result[2][0], 1)

['The quick brown dog jumps over the lazy fox', 'The fast hazel hound skips above the inactive tod.']


In [491]:
ngrams1

Counter({('the', 'quick'): 1,
         ('quick', 'brown'): 1,
         ('brown', 'dog'): 1,
         ('dog', 'jumps'): 1,
         ('jumps', 'over'): 1,
         ('over', 'the'): 1,
         ('the', 'lazy'): 1,
         ('lazy', 'fox'): 1})

In [492]:
embeddings_target = bert_embedding([' '.join(elem)for elem in list(ngrams1.keys())])
embeddings_predictions = bert_embedding([' '.join(elem)for elem in list(ngrams2.keys())])
    

In [493]:
len(embeddings_target[1][1])

2

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

def fmeasure(precision, recall):
  """Computes f-measure given precision and recall values."""

  if precision + recall > 0:
    return 2 * precision * recall / (precision + recall)
  else:
    return 0.0

def cos_sim(emb1, emb2):
    return cosine_similarity(emb1.reshape(1, -1), emb2.reshape(1, -1))

def count_ngram_overlap(ngram1_embs, ngram2_embs): #The idea count cousine similarity to every pair. If > 0.6 than add
    result = 1
    #print ("ngram1_embs", len(ngram1_embs), len(ngram1_embs[0]))
    for elem in ngram1_embs: # по словам в н-граме
        similarities = [cos_sim(elem, elem2)[0][0] if cos_sim(elem, elem2) >= 0.6 else 0 for elem2 in ngram2_embs]
        #print (similarities)
        max_ = max(similarities)
        result *= max_
    return result
        

def count_overlap(ngram, ngram_emb, list_of_ngrams2, list_of_ngrams2_embs): # only if ngram not in list_of_ngrams !!!
    overlaps = [count_ngram_overlap(ngram_emb, elem[1]) for elem in list_of_ngrams2_embs] # по всем н-грамам
    return max(overlaps)

def score_ngrams(target_ngrams, prediction_ngrams):
    intersection_ngrams_count = 0
    
    #print ("target_ngrams", target_ngrams)
    #print ("prediction_ngrams", prediction_ngrams)
    
    embeddings_target = bert_embedding([' '.join(elem)for elem in list(target_ngrams.keys())])
    embeddings_predictions = bert_embedding([' '.join(elem)for elem in list(prediction_ngrams.keys())])
    
    for ind, ngram in enumerate(list(target_ngrams.keys())):
        #print ("ind", ind)
        intersection_ngrams_count += min(target_ngrams[ngram],
                                         prediction_ngrams[ngram])
        if (min(target_ngrams[ngram], prediction_ngrams[ngram]) == 0):
            #print ("ngram", ngram)
            #print ('overlap')
            overlap_ngram = count_overlap(ngram, embeddings_target[ind][1], prediction_ngrams, embeddings_predictions) #по всем н-грамам
            #print ('overlap ngram', overlap_ngram)
            intersection_ngrams_count += overlap_ngram
            
    target_ngrams_count = sum(target_ngrams.values())
    prediction_ngrams_count = sum(prediction_ngrams.values())
    
    #print ("intersection_ngrams_count", intersection_ngrams_count)
    #print ("intersection_targets_count", prediction_ngrams_count, target_ngrams_count)


    precision = intersection_ngrams_count / max(prediction_ngrams_count, 1)
    recall = intersection_ngrams_count / max(target_ngrams_count, 1)
    print (precision, recall)
    
    f = fmeasure(precision, recall)
    return f, precision, recall

In [507]:
score_ngrams(ngrams01, ngrams02)

0.6794479370117188 0.7549421522352431


(0.7152083547491778, 0.6794479370117188, 0.7549421522352431)

In [508]:
score_ngrams(ngrams01, ngrams01)

1.0 1.0


(1.0, 1.0, 1.0)

In [509]:
score_ngrams(ngrams01, ngrams02)

0.6794479370117188 0.7549421522352431


(0.7152083547491778, 0.6794479370117188, 0.7549421522352431)

In [510]:
score_ngrams(ngrams01, ngrams03)

0.5479773506522179 0.487090978357527


(0.5157433888491462, 0.5479773506522179, 0.487090978357527)

In [392]:
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)
scores = scorer.score('The quick brown dog jumps over the lazy fox',
                      'The fast hazel hound skips above inactive tod.')
print (scores)

{'rouge1': Score(precision=0.125, recall=0.1111111111111111, fmeasure=0.11764705882352941), 'rouge2': Score(precision=0.0, recall=0.0, fmeasure=0.0)}


In [ ]:
len(result[0][0])

In [ ]:
len(result[0][])

In [280]:
from bert_embedding import BertEmbedding

bert_abstract = """The quick brown dog jumps over the lazy fox.\n The fast hazel hound skips above inactive tod. \n Just the place for a Snark the Bellman cried"""
sentences = bert_abstract.split('\n')
print (sentences)
bert_embedding = BertEmbedding()
result = bert_embedding(sentences)

['The quick brown dog jumps over the lazy fox.', ' The fast hazel hound skips above inactive tod. ', ' Just the place for a Snark the Bellman cried']


## Our answer

In [159]:
import six
from six.moves import map
from six.moves import range

In [160]:
for ngram in six.iterkeys(ngrams1):
    print (ngram)
    print (ngrams1[ngram])
    print (ngrams2[ngram])
    print (min(ngrams1[ngram], ngrams2[ngram]))
    intersection_ngrams_count += min(ngrams1[ngram], ngrams2[ngram])
    

('The', 'quick')
1
0
0


NameError: name 'intersection_ngrams_count' is not defined

In [7]:
def _score_ngrams(target_ngrams, prediction_ngrams):
      """Compute n-gram based rouge scores.
      Args:
        target_ngrams: A Counter object mapping each ngram to number of
          occurrences for the target text.
        prediction_ngrams: A Counter object mapping each ngram to number of
          occurrences for the prediction text.
      Returns:
        A Score object containing computed scores.
      """

      intersection_ngrams_count = 0
      for ngram in six.iterkeys(target_ngrams):
        intersection_ngrams_count += min(target_ngrams[ngram],
                                         prediction_ngrams[ngram])
      target_ngrams_count = sum(target_ngrams.values())
      prediction_ngrams_count = sum(prediction_ngrams.values())

      precision = intersection_ngrams_count / max(prediction_ngrams_count, 1)
      recall = intersection_ngrams_count / max(target_ngrams_count, 1)
      fmeasure = scoring.fmeasure(precision, recall)

      return scoring.Score(precision=precision, recall=recall, fmeasure=fmeasure)

In [8]:
## Measure

In [1]:
import pandas as pd 
# Read data from file 'filename.csv' 
# (in the same directory that your python process is based)
# Control delimiters, rows, column names with read_csv (see later) 
data = pd.read_csv("Evaluation dataset - Sheet1.csv") 
# Preview the first 5 lines of the loaded data 
data.head()

domain    object_a  object_b  \
0   brands      toyota     honda   
1   brands       nokia  motorola   
2   brands       nokia   samsung   
3  compsci  Javascript       PHP   
4  compsci        Perl      Ruby   

                                              Q1 url  \
0  https://www.quora.com/Which-is-a-more-reliable...   
1  https://www.quora.com/Which-brand-or-company-i...   
2  https://www.theverge.com/2019/9/2/20844444/and...   
3  https://www.bitdegree.org/tutorials/php-vs-jav...   
4               https://www.educba.com/perl-vs-ruby/   

                                                  Q1  \
0  I wrote this to answer another question on Quo...   
1  Motorola has a history of making good android ...   
2  Share All sharing options for: Nokia is better...   
3  In the PHP vs. JavaScript discussion, it is im...   
4  Perl is an ideal choice for system administrat...   

                                              Q2 url  \
0  https://www.quora.com/Which-is-a-more-reliable...   
1  https://www.quora.com/Which-brand-or-company-i...   
2  https://www.quora.com/Is-Nokia-better-than-Sam...   
3  https://www.quora.com/Is-PHP-better-than-JavaS...   
4  https://www.quora.com/As-someone-who-knows-Rub...   

                                                  Q2  \
0  I drive a Honda and my wife a Toyota. So by ow...   
1  Well, it depends what you expect from a phone....   
2  At present Samsung is better than Nokia.Since,...   
3  I would normally say “it depends” for a questi...   
4  I know a lot more Ruby than Perl, but the prim...   

                                              Q3 url  \
0  https://www.autogravity.com/autogravitas/cars/...   
1  https://www.quora.com/Which-brand-or-company-i...   
2  https://www.quora.com/Is-Nokia-better-than-Sam...   
3  https://www.quora.com/Is-PHP-better-than-JavaS...   
4  https://www.coursereport.com/blog/ruby-vs-pyth...   

                                                  Q3  Q4 url  Q4  Q5 url  Q5  
0  In terms of sheer corporate value, Toyota is t...     NaN NaN     NaN NaN  
1  Motorola is best .Its always a branded better ...     NaN NaN     NaN NaN  
2  In my opinion i would say Nokia.. If you want ...     NaN NaN     NaN NaN  
3  PHP is generally easier for people to learn si...     NaN NaN     NaN NaN  
4  https://www.quora.com/As-someone-who-knows-Rub...     NaN NaN     NaN NaN

In [2]:
target1 = data['Q2'][0]

In [3]:
data['Q1'][0]

'I wrote this to answer another question on Quora but it very effectively addresses this question as well. '

In [4]:
target2 = data['Q3'][0]

In [58]:
gen_templates = 'After much thought, I realized that Honda is better, because: quicker, bigger, nicer, weaker, but toyota is lighter, easier, faster, softer.'

In [59]:
small = "I've used the Honda the past few years, and they're pretty good. They're just not as fast as a Toyota, but they're much more powerful, lighter, and more durable than the Toyota. They're more comfortable, they're more comfortable, and they're better.have been using the Honda for a while, and I can tell you that they're very good. They're just not as fast as a Toyota, but they're much more powerful, lighter, and more durable than the Toyota. They're more comfortable, they're more comfortable, and thy're better. They're just not as good as the Honda."

In [7]:
big = "They don\'t have that kind of engine. Maybe they are trying to make this bigger, faster, more powerful. You cannot afford to have a car with a big engine. You need to be careful when you make a big engine. There is no point, because it will explode. There is no point in spending a lot of money on a big engine.(CNN) After the shooting deaths of five police officers in Dallas last week, President Barack Obama offered condolences to the families of the fallen officers, calling the situation an attack on our shared humanity.Yet more than two months after the deaths of Alton Sterling in Louisiana and Philando Castile in Minnesota, the President did not issue a statement or call for unity or reflection. While we mourn for the officers who lost their lives in Dallas, we do not yet know the full extent of the threat that this attack represents, Obama said in a statement."

In [54]:
small

"I've used the Honda the past few years, and they're pretty good. They're just not as fast as a Toyota, but they're much more powerful, lighter, and more durable than the Toyota. They're more comfortable, they're more comfortable, and they're better.have been using the Honda for a while, and I can tell you that they're very good. They're just not as fast as a Toyota, but they're much more powerful, lighter, and more durable than the Toyota. They're more comfortable, they're more comfortable, and thy're better. They're just not as good as the Honda."

In [75]:
result = bert_embedding([gen_templates])

In [79]:
from nltk.stem import porter
from nltk.tokenize import TweetTokenizer


stemmer = porter.PorterStemmer()
tokenizer = TweetTokenizer()

In [81]:


ngrams1 = create_ngrams(tokenizer.tokenize(gen_templates), 2)
ngrams2= create_ngrams(tokenizer.tokenize(small), 2)
ngrams3= create_ngrams(tokenizer.tokenize(big), 2)

ngrams01 = create_ngrams(tokenizer.tokenize(gen_templates), 1)
ngrams02= create_ngrams(tokenizer.tokenize(small), 1)
ngrams03= create_ngrams(tokenizer.tokenize(big), 1)

In [49]:
gen_templates

'After much thought, I realized that Honda is better, because: quicker, bigger, nicer, weaker, but Toyota is lighter, easier, faster, softer.'

In [94]:

ngrams1_t = create_ngrams(tokenizer.tokenize(target1), 2)
ngrams2_t= create_ngrams(tokenizer.tokenize(target2), 2)

ngrams01_t = create_ngrams(tokenizer.tokenize(target1), 1)
ngrams02_t = create_ngrams(tokenizer.tokenize(target2), 1)


In [92]:
score_ngrams(ngrams01, ngrams01_t)

0.0821059115319384 0.6491498630493879


(0.14577400433389767, 0.0821059115319384, 0.6491498630493879)

In [95]:
score_ngrams(ngrams01, ngrams02_t)

0.38255592389982573 0.5857887584716082


(0.4628454387923817, 0.38255592389982573, 0.5857887584716082)

In [97]:
score_ngrams(ngrams02, ngrams01_t)

0.22225900106279275 0.5020672077579158


(0.30811795763773464, 0.22225900106279275, 0.5020672077579158)

In [98]:
score_ngrams(ngrams02, ngrams02_t)

0.7212211319378444 0.31553424522280693


(0.439004167266514, 0.7212211319378444, 0.31553424522280693)

In [100]:
score_ngrams(ngrams03, ngrams01_t)

0.4667321349321147 0.6709274439649149


(0.5505045694071096, 0.4667321349321147, 0.6709274439649149)

In [99]:
score_ngrams(ngrams03, ngrams02_t)

1.6459892696263838 0.4582583762028001


(0.7169197707706028, 1.6459892696263838, 0.4582583762028001)

In [91]:
ngrams1_t

Counter({('I', 'drive'): 1,
         ('drive', 'a'): 1,
         ('a', 'Honda'): 1,
         ('Honda', 'and'): 1,
         ('and', 'my'): 1,
         ('my', 'wife'): 1,
         ('wife', 'a'): 1,
         ('a', 'Toyota'): 1,
         ('Toyota', '.'): 1,
         ('.', 'So'): 1,
         ('So', 'by'): 1,
         ('by', 'owning'): 1,
         ('owning', 'both'): 1,
         ('both', 'cars'): 1,
         ('cars', 'I'): 1,
         ('I', 'have'): 1,
         ('have', 'experienced'): 1,
         ('experienced', 'both'): 1,
         ('both', 'brands'): 2,
         ('brands', '.'): 2,
         ('.', 'I'): 1,
         ('I', '’'): 1,
         ('’', 've'): 1,
         ('ve', 'been'): 1,
         ('been', 'driving'): 1,
         ('driving', 'a'): 1,
         ('a', 'honda'): 1,
         ('honda', 'city'): 1,
         ('city', 'AT'): 1,
         ('AT', 'for'): 1,
         ('for', 'almost'): 1,
         ('almost', '7'): 1,
         ('7', 'years'): 1,
         ('years', 'and'): 1,
         ('and', '

In [28]:
from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)
scores = scorer.score(gen_templates, target1)
scores

In [29]:
scores

{'rouge1': Score(precision=0.025974025974025976, recall=0.2857142857142857, fmeasure=0.04761904761904762),
 'rouge2': Score(precision=0.004347826086956522, recall=0.05, fmeasure=0.008)}

In [30]:
from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)
scores = scorer.score(small, target1)
scores

{'rouge1': Score(precision=0.17316017316017315, recall=0.3669724770642202, fmeasure=0.2352941176470588),
 'rouge2': Score(precision=0.02608695652173913, recall=0.05555555555555555, fmeasure=0.03550295857988165)}

In [31]:
from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)
scores = scorer.score(big, target1)
scores

{'rouge1': Score(precision=0.23809523809523808, recall=0.34375, fmeasure=0.28132992327365725),
 'rouge2': Score(precision=0.02608695652173913, recall=0.03773584905660377, fmeasure=0.030848329048843187)}

In [42]:
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)
scores = scorer.score(target1, gen_templates)
scores

{'rouge1': Score(precision=0.2857142857142857, recall=0.025974025974025976, fmeasure=0.04761904761904762),
 'rouge2': Score(precision=0.05, recall=0.004347826086956522, fmeasure=0.008)}

In [36]:
target2

"In terms of sheer corporate value, Toyota is the most successful, preponderant automaker in the world. Honda is much smaller with an overall value that's just 25 percent of Toyota's. Toyota also sells many more vehicles in the United States every year than Honda."